ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls', namespace='todolist')),
    path('register_login/', include('register_login.urls', namespace='register_login')),
]

register_login/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'register_login'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/Login.html'), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),

    path('reset_password_completed/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_completed"),
    path('email_confirmation/', EmailConfirmation.as_view(), name='email_confirmation'),
    path('email_confirmation/<int:pk>/', AccountActivation.as_view(), name='email_verifying'),
    path('profile/', Profile.as_view(), name='profile'),
]

todolist/urls.py
from django.urls import path
from .views import WorksList, FilterView, GetChildren, index, AddComment, DeleteWork, DeleteComment, DoneWork, \
    update_work

app_name = 'todolist'

urlpatterns = [
    path('', index, name='index'),
    path('list/', WorksList.as_view(), name='list'),
    path('filter/', FilterView.as_view(), name='filter'),
    path('list/children/<int:pk>/', GetChildren.as_view(), name='get_children'),
    path('add_comment/<int:pk>/', AddComment.as_view(), name='add_comment'),
    path('<pk>/delete', DeleteWork.as_view(), name='delete'),
    path('<pk>/delete/comment/', DeleteComment.as_view(), name='delete_comment'),
    path('list/done/<pk>/', DoneWork.as_view(), name='done_work'),
    path('update/<pk>/', update_work, name='update_work')
]

todolist/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

PRIORITY_CHOICES = (
    ('without', 0),
    ('first', 1),
    ('second', 2),
    ('third', 3),
)


class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tree = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')
    title = models.CharField(max_length=75)
    description = models.TextField(blank=True)
    due_date = models.DateTimeField()
    create_at = models.DateTimeField(auto_now_add=True)
    done = models.BooleanField(default=False)
    priority = models.CharField(choices=PRIORITY_CHOICES, max_length=10)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ToDoList, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('todolist:get_children', kwargs={'pk': self.pk})


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    for_work = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    comment = models.CharField(max_length=250, blank=True)

todolist/forms.py
from django.forms import ModelForm
from django import forms
from .models import ToDoList, PRIORITY_CHOICES, Comment


class AddWorkForm(ModelForm):
    class Meta:
        model = ToDoList
        fields = ['title', 'description', 'due_date', 'priority']

        widgets = {
            'title': forms.TextInput(attrs={
                'class': "form-control form-control-lg border-0 add-todo-input bg-transparent rounded w-25 mt-1 mx-3",
                'label': 'Title',
                'placeholder': 'Add new work...'
            }),
            'description': forms.Textarea(attrs={
                'class': "form-floating form-control w-25 mx-3",
                'placeholder': 'description'
            }),
            'priority': forms.Select(attrs={
                'class': 'form-select w-25 mx-3',
            }),
            'due_date': forms.DateInput(attrs={'class': 'form-control w-25 mx-3', 'id': 'due_date',
                                               })
        }


class FilterForm(forms.Form):
    priority = forms.ChoiceField(choices=PRIORITY_CHOICES)
    due_date = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M'], widget=forms.DateInput(
        attrs={'class': 'form-control w-25 mx-3',
               'id': 'due_date'}))
    done = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        self.fields['priority'].widget.attrs.update({
            'class': 'form-select w-25 mx-3',
        }),
        self.fields['done'].widget.attrs.update({
            'class': 'form-check-label mx-3',
        }),


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['comment'].widget.attrs.update({
            'class': 'form-control w-25 mx-3 mt-2'
        })


class UpdateWorkForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = ['title', 'description', 'due_date', 'priority']

    def __init__(self, *args, **kwargs):
        super(UpdateWorkForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': "form-control form-control-lg",
            'label': 'Title',
            'placeholder': 'Add new work...'
        }),
        self.fields['description'].widget.attrs.update({
            'class': "form-floating form-control",
            'placeholder': 'description'
        }),
        self.fields['priority'].widget.attrs.update({
            'class': 'form-select input-sm'
        }),
        self.fields['due_date'].widget.attrs.update({
            'class': 'form-control input-sm', 'id': 'due_date',
        }),

todolist/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, FieldError, ValidationError
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View

from .models import ToDoList, Comment
from .forms import AddWorkForm, FilterForm, CommentForm, UpdateWorkForm

from django.views.generic import ListView
from django.views.generic.edit import DeleteView, UpdateView


def index(request):
    return render(request, 'todolist/base.html')


@method_decorator(login_required, name='dispatch')
class WorksList(ListView):
    model = ToDoList
    template_name = 'todolist/works.html'

    def get_queryset(self):
        obj = super().get_queryset()
        today = datetime.date.today()
        return obj.filter(user=self.request.user, due_date=today, tree=None).order_by('priority')

    def get_context_data(self, *, object_list=None, **kwargs):
        object_list = super().get_context_data(**kwargs)
        object_list['form'] = AddWorkForm()
        return object_list

    def post(self, request, *args, **kwargs):
        try:
            obj = ToDoList.objects.create(
                user=request.user,
                title=request.POST.get('title'),
                due_date=request.POST.get('due_date'),
                description=request.POST.get('description'),
                priority=request.POST.get('priority'),
            )
            obj.save()
            messages.add_message(request, messages.SUCCESS, "Your work has been saved successfully!")
            return redirect('todolist:list')
        except FieldError:
            messages.add_message(request, messages.ERROR, "Your work has been saved successfully!")
            return redirect('todolist:list')
        except ValidationError:
            messages.add_message(request, messages.ERROR, "there are some validation errors!")
            return redirect('todolist:list')


@method_decorator(login_required, name='dispatch')
class GetChildren(View):
    def get(self, *args, **kwargs):
        form = AddWorkForm()
        comment_form = CommentForm()
        work = ToDoList.objects.get(user=self.request.user, pk=self.kwargs['pk'])
        comments = Comment.objects.filter(user=self.request.user, for_work=work)
        children = work.children.all()
        return render(self.request, 'todolist/children.html', {'children': children, 'work': work,
                                                               'comments': comments, 'form': form,
                                                               'comment_form': comment_form})

    def post(self, *args, **kwargs):
        request = self.request
        work = ToDoList.objects.get(user=self.request.user, pk=self.kwargs['pk'])
        obj = ToDoList.objects.create(
            user=request.user,
            title=request.POST.get('title'),
            tree=work,
            due_date=request.POST.get('due_date'),
            description=request.POST.get('description'),
            priority=request.POST.get('priority'),
        )
        obj.save()
        url = work.get_absolute_url()
        return redirect(url)

# Update works class based view!
# class UpdateWork(UpdateView):
#     model = ToDoList
#     fields = ['title', 'description', 'due_date', 'priority']
#     template_name_suffix = '_update_form'


def update_work(request, pk):
    obj = get_object_or_404(ToDoList, pk=pk)
    form = UpdateWorkForm(request.POST or None, instance=obj)
    if request.method == 'POST':
        if form.is_valid():
            url = obj.get_absolute_url()
            form.save()
            return redirect(url)
    return render(request, 'todolist/todolist_update_form.html', context={'form': form})


@method_decorator(login_required, name='dispatch')
class AddComment(View):
    def post(self, request, *args, **kwargs):
        work = ToDoList.objects.get(user=self.request.user, pk=self.kwargs['pk'])
        obj = Comment.objects.create(
            for_work=work,
            user=request.user,
            comment=request.POST.get('comment')
        )
        obj.save()
        url = work.get_absolute_url()
        return redirect(url)


@method_decorator(login_required, name='dispatch')
class DoneWork(View):
    def post(self, request, *args, **kwargs):
        work = ToDoList.objects.get(user=request.user, pk=kwargs['pk'])
        url = reverse('todolist:get_children', kwargs={'pk': self.kwargs['pk']})
        done = request.POST.get('done')
        page = request.POST.get('page')
        # Handle changing done field for filter page and return filter page
        if page == 'filter':
            if done == 'True':
                work.done = True
                work.save()
                return redirect('todolist:filter')
            else:
                work.done = False
                work.save()
            return redirect('todolist:filter')
        # Handle changing done field for children page and return children page
        else:
            if done == 'True':
                work.done = True
                work.save()
                return redirect(url)
            else:
                work.done = False
                work.save()
            return redirect(url)


@method_decorator(login_required, name='dispatch')
class DeleteWork(DeleteView):
    model = ToDoList
    success_url = reverse_lazy('todolist:list')


@method_decorator(login_required, name='dispatch')
class DeleteComment(DeleteView):
    model = Comment
    success_url = reverse_lazy('todolist:list')

    # Handle deleting without confirm page
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class FilterView(ListView):
    template_name = 'todolist/filter.html'
    today = datetime.date.today()

    def get_queryset(self):
        obj = ToDoList.objects.filter(user=self.request.user)
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FilterForm()
        return context

    def post(self, request):
        form = FilterForm(data=request.POST)
        get_field = lambda f: request.POST.get(f)
        due_date = get_field('due_date')
        priority = get_field('priority')
        done = get_field('done')
        user = request.user
        obj = self.get_queryset()
        if due_date:
            obj = obj.filter(due_date=due_date)
        else:
            pass
        if priority:
            obj = obj.filter(priority=priority)
        else:
            pass
        if done == 'on':
            done = True
        else:
            done = False
        if done:
            obj = obj.filter(done=done)
        else:
            pass
        return render(request, template_name='todolist/filter.html', context={'object_list': obj, 'form': form})

todolist/templates/todolist/base.html
<!DOCTYPE html>
{% load bootstrap5 %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}ToDoList{% endblock %}</title>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

    {% bootstrap_css %}
</head>

<body>
  <div class="container-sm">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todolist:index' %}">ToDoList</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="nav navbar-nav">
            <li><a class="nav-link active" aria-current="page" href="{% url 'todolist:list' %}">Works</a></li>
            <li><a class="nav-link" href="{% url 'todolist:filter' %}">Filter</a></li>
            <li><a class="nav-link" href="{% url 'register_login:profile' %}">Profile</a></li>
          </ul>
        </div>
      </div>
      <div class="container-fluid">
        <div class="d-flex">
            {% if user.is_authenticated %}
                <div style="margin-left: 230px">Welcome {{ user.username }}</div>
                <div style="margin-left:10px"><a href="{% url 'register_login:logout' %}">LogOut</a></div>
            {% else %}
                <div style="margin-left: 230px">please login</div>
                <div style="margin-left:10px"><a href="{% url 'register_login:login' %}">Login</a></div>
            {% endif %}
        </div>
      </div>
    </nav>
  </div>

<nav class="navbar fixed-bottom navbar-light bg-light">
  <div class="container-fluid">
    <p style="margin-left: 450px" class="navbar-nav">created by matinmat8</p>
  </div>
</nav>

  {% if messages %}
    {% for message in messages %}
      <div class="container-sm mt-3 alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
        {{ message | safe }}
      </div>
    {% endfor %}
  {% endif %}

    <div>
        <main>
            {% block main_content %}
              <div  class="container-sm mt-3">
                  <h3>ToDoList App</h3>
                  <p class="lead">This is a web application for scheduling your tasks, and in order not to forget your tasks,
                      we recommend that you create an account and plan your tasks. </p>
              </div>
            {% endblock %}
        </main>

        <footer>
            {% block footer %}
            {% endblock %}
        </footer>

    </div>
    <script>
        {% block javascript %}
             $(function () {
                $("#due_date").datepicker({
                  format:'yyyy-mm-dd',
                });
              });

            function ShowForm() {
               document.getElementById('Add-Work').style.display = "none";
               document.getElementById('form').style.display = "block";
            };
            // send form for work object
            function send_true() {
                document.getElementById('done').submit();
            };

            function send_false() {
                document.getElementById('done_false').submit();
            };

            // send form for child object
            function send_form_true() {
                document.getElementById('done_form_true').submit();
            };
            function send_form_false() {
                 document.getElementById('done_form_false').submit();
            }

        {% endblock %}
    </script>
</body>
</html>

todolist/templates/todolist/children.html
{% extends 'todolist/base.html' %}

{% block title %}ToDoList Children{% endblock %}

{% block main_content %}
  <div class="container-sm mt-3">
    <p style="font-size:large">{{ work.title }}</p>
    <p style="font-size:small; color:#303841">{{ work.description }}</p>
    <p style="font-size:small; display:inline; margin-right:10px; color:gray">{{ work.due_date }}</p>

    <!-- Handle done form -->
    {% if work.done %}
      <form style="display:inline; margin-right:15px" id="done" method="post" action="{% url 'todolist:done_work' work.pk %}">
          {% csrf_token %}
          <label style="color:gray;">Done:</label>
          <input name="done" class="form-check-input" type="checkbox" onclick="send_true()" value="False" checked>
      </form>
    {% else %}
      <form style="display:inline; margin-right:15px" id="done_false" method="post" action="{% url 'todolist:done_work' work.pk %}">
          {% csrf_token %}
          <label style="color:gray;">Done:</label>
          <input name="done" class="form-check-input" type="checkbox" value="True" onclick="send_false()">
      </form>
    {% endif %}
    <!-- end of the done form -->

    <a  class="link-secondary" href="{% url 'todolist:delete' work.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
      </svg>
    </a>
    <a class="link-secondary" href="{% url 'todolist:update_work' work.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
      </svg>
    </a>
    <br>
    <h4>comments</h4>
      <form method="post" action="{% url 'todolist:add_comment' work.pk %}">
          {% csrf_token %}
          {{ comment_form.as_p }}
          <button style="display: inline; margin:-85px 0 0 260px" class="btn btn-dark btn-sm" type="submit">Add</button>
      </form>
    {% for comment in comments %}
        <p style="font-size:small; display:inline; color:#303841" class="mx-3">{{ comment.comment }}</p>
        <a href="{% url 'todolist:delete_comment' comment.pk %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
            </svg>
        </a>
    {% empty %}
        <p style="font-size:small; color:#303841" class="mx-3">There is no comment yet, you can add some</p>
    {% endfor %}
    <hr>
    <br>
  </div>

{% endblock %}

{% block footer %}

<h4 style="margin-left:85px">Children</h4>
{% for child in children %}
        <div style="margin-left:100px" class="container-sm mt-3">
            <a href="{{ child.get_absolute_url }}" style="font-size:large">{{ child.title }}</a>
            <p style="font-size:small; color:#303841">{{ child.description }}</p>
            <p style="font-size:small; display:inline; color:gray">{{ child.due_date }}</p>

            <!-- Handle done form -->
            {% if child.done %}
              <form style="display:inline; margin-right:15px" id="done_form_true" method="post" action="{% url 'todolist:done_work' child.pk %}">
                  {% csrf_token %}
                  <label style="color:gray;">Done:</label>
                  <input name="done" class="form-check-input" type="checkbox" onclick="send_form_true()" value="False" checked>
              </form>
            {% else %}
              <form style="display:inline; margin-right:15px" id="done_form_false" method="post" action="{% url 'todolist:done_work' child.pk %}">
                  {% csrf_token %}
                  <label style="color:gray;">Done:</label>
                  <input name="done" class="form-check-input" type="checkbox" onclick="send_form_false()" value="True">
              </form>
            {% endif %}
            <!-- end of the done form -->

            <a  class="link-secondary" href="{% url 'todolist:delete' work.pk %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                </svg>
            </a>
            <a class="link-secondary" href="{% url 'todolist:update_work' work.pk %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
            </a>
        </div>
        <br>
{% empty %}
    <p style="margin-left:100px">There are no children, you can add</p>
{% endfor %}

<div class="container-sm">
    <hr>
</div>

<h4 style="margin:30px 0 15px 85px;">Add Children</h4>
  <div class="container-sm mb-5">
    <form style="margin:30px 0 15px 0; display:none;" id="form" method="POST" action="{% url 'todolist:get_children' work.pk %}">
      {{ form.as_p }}
      {% csrf_token %}
      <input class="btn btn-dark" id="button" type="submit">
    </form>
    <button style="margin:15px 0 15px 0;" type="button" onclick="ShowForm()" id="Add-Work" class="btn btn-dark">Add Child +</button>
  </div>

{% endblock %}

todolist/templates/todolist/filter.html
{% extends 'todolist/base.html' %}

{% block title %}Tasks Filtering{% endblock %}


{% block main_content %}
    <div class="container-sm mt-2">
        <form id="form" method="POST" action="{% url 'todolist:filter' %}">
          {{ form.as_p }}
          {% csrf_token %}
          <input class="btn btn-dark" id="button" type="submit">
        </form>
    </div>
    {% for obj in object_list %}
        <div class="container-sm mt-3">
            <a href="{{ obj.get_absolute_url }}" style="font-size:large">{{ obj.title }}</a>
            <p style="font-size:small; color:#303841">{{ obj.description }}</p>
            <p style="font-size:small; display:inline; margin-right:10px; color:#303841">{{ obj.due_date }}</p>

            <!-- Handle done form -->
            {% if obj.done %}
              <form style="display:inline; margin-right:15px" id="done" method="post" action="{% url 'todolist:done_work' obj.pk %}">
                  {% csrf_token %}
                  <label style="color:gray;">Done:</label>
                  <input name="done" class="form-check-input" type="checkbox" onclick="send_true()" value="False" checked>
                  <input type="hidden" value="filter" name="page">
              </form>
            {% else %}
              <form style="display:inline; margin-right:15px" id="done_false" method="post" action="{% url 'todolist:done_work' obj.pk %}">
                  {% csrf_token %}
                  <label style="color:gray;">Done:</label>
                  <input name="done" class="form-check-input" type="checkbox" value="True" onclick="send_false()">
                  <input type="hidden" value="filter" name="page">
              </form>
            {% endif %}
            <!-- end of the done form -->

            <a  class="link-secondary" href="{% url 'todolist:delete' obj.pk %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                </svg>
            </a>
        </div>
        <hr>
        <br>
    {% endfor %}
{% endblock %}